import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../components/Header"; 
import "../styles/globals.css";
import Head from "next/head"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Health Hub",  
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const title = String(metadata.title || "Default Title");
  const description = String(metadata.description || "Default description");

  return (
    <html lang="en">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0 }}
      >
        <Header />
        <main style={{ padding: '20px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}